Part2
daydre3001/PFMCPP_Project3 pull request #2
Opened 2021-06-11 14:14 UTC by daydre3001

2021-06-11 21:11 UTC, matkatmusic requested changes

2021-06-11 21:11 UTC, matkatmusic commented on main.cpp
> +}
2 things: 
1) You can express this logic with a ternary expression:
```
float totalCost = (panSize > 18) ? PizzaCost * 2 : PizzaCost;
```
2) function parameter names follow the same naming rules as variables: use `camelCase`
- [ ] revise

2021-06-11 21:11 UTC, matkatmusic commented on main.cpp
> +}
`status` should be a member variable, so that it's value will persist between this function and `engineStop()`
- [ ] make `status` a member variable, not a function parameter.

2021-06-11 21:11 UTC, matkatmusic commented on main.cpp
> +    }
make `status` a member variable, not a function parameter
- [ ] revise

2021-06-11 21:11 UTC, matkatmusic commented on main.cpp
> +}
if these two functions being called return `float`, then you can write:
```
return consumption.currentFuelLevel() / flowRate.calculateFuelFlow();
```
- [ ] inspect and revise

2021-06-12 14:28 UTC, daydre3001 commented on main.cpp
> +}
This member function now modifies the member variable `onStatus`

2021-06-12 14:28 UTC, daydre3001 commented on main.cpp
> +    }
This member function now modifies the member variable `onStatus`

2021-06-12 20:44 UTC, matkatmusic requested changes

2021-06-12 20:44 UTC, matkatmusic commented on main.cpp
> +    {
Function arguments need to follow the variable naming rules.
`useCamelCaseToNameThem`
- [ ] revise

2021-06-12 21:02 UTC, matkatmusic approved these changes

2021-06-12 21:03 UTC, merged